<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'comment_notice_subject'				=> "A new comment has been left on <a href='%s'>%s</a>",
'comment_notifications'				=> "<#NAME#>,

<#AUTHOR#> has just commented on \"<#TITLE#>\", here: <#URL#>.

<div class='callout'><#COMMENT#></div>

You can review the new comment here:
<#COMMENTURL#>",
'comment_button_post'				=> "Add Comment",
'check_all'				=> "Check all",
'report_link'				=> "Report",
'view_comment'				=> "View comment",
'reply_to_comment'				=> "Reply directly to this comment",
'comment_reply'				=> "Quote",
'mq_image_add'				=> "MultiQuote",
'view_it_anyway'				=> "View it anyway?",
'permalink'				=> "Permalink:",
'approve_link'				=> "Approve",
'ignored_comments_not'				=> "This comment is hidden because you have chosen to ignore posts by",
'unhide_link'				=> "Unhide",
'hide_link'				=> "Hide",
'edit_link'				=> "Edit",
'delete_link'				=> "Delete",
'delete_comment'				=> "Delete comment",
'edit_comment'				=> "Editing comment from:",
'comment_save'				=> "Save",
'comments_act_go'				=> "Go",
'delete_x_comments'				=> "Delete",
'unhide_x_comments'				=> "Unhide",
'hide_x_comments'				=> "Hide",
'unapprove_x_comments'				=> "Un-approve",
'approve_x_comments'				=> "Approve",
'comment_action_count'				=> "With <span id='comment_count'>#{count}</span> checked comments:",
'manage_comments_pop'				=> "Manage Comments",
'comm_confirm_hide'				=> "Hide Comment",
'comm_confirm_hide_desc'				=> "This option hides the comment, but moderators may still be able to view it.",
'comments_header'				=> "Comments",
'click here to login'				=> "click here to log in",
'comment_approval_required'				=> "Your comment requires moderator approval before it will be shown.",
'del_comm_now'				=> "Delete comment now",
'comm_confirm_delete_desc'				=> "Are you sure you want to delete this comment?",
'comm_confirm_delete'				=> "Confirm Delete",
'comment_permalink'				=> "Get the permalink",
'mobile_add_comment'				=> "Add Comment",
'yourname_captcha'				=> "Your Name:",
'sign_in'				=> "Sign In",
'post_deleted_by'				=> "Comment Hidden By",
'comment_hidden_content'				=> "Toggle Content",
'no_reason_given'				=> "No Reason Given",
 ); 
