<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'enter_username'				=> "Username",
'ipb_login'				=> "IP.Board: Log in",
'enter_name_and_email'				=> "Username / Email",
'enter_useremail'				=> "Email Address",
'logout_complete'				=> "Log out complete",
'no_acp_access'				=> "You do not have permission to access the ACP",
'bad_email_password'				=> "Your login credentials were not valid",
 ); 
