<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'invalid_option'				=> "Invalid Option Selected",
'click_here_link'				=> "Click here",
'to_view_allrep'				=> "to view all reports.",
'report_prune_2'				=> "days old",
'only_active_note'				=> "Only active reports are currently being displayed.",
'report_reply'				=> "
<#MOD_NAME#>,

<#COMMENTER#> has made a comment on a report you have access to in our report center.

------------------------------------------------

Content Reported: <#LINK#> 
Report Link: <#REPORTLINK#>

------------------------------------------------
Comment:

<#COMMENT#>

------------------------------------------------
",
'report_emailpm'				=> "
<#MOD_NAME#>,

You have been sent this communication from <#USERNAME#> via the \"Report this to a moderator\" link.

------------------------------------------------

Content Reported: <#LINK#> 
Report Link: <#REPORTLINK#>

------------------------------------------------
Report:

<#REPORT#>

------------------------------------------------
",
'subject_report_guest'				=> "%s has <a href='%s'>reported</a> <a href='%s'>something</a>",
'report_msg_msg'				=> "<strong>Enter your report</strong><br /><br />",
'subject_report'				=> "<a href='%s'>%s</a> has <a href='%s'>reported</a> <a href='%s'>something</a>",
'report_msg_title'				=> "Private Message Title",
'report_msg_page'				=> "Report this message to a moderator",
'report_file_msg'				=> "<strong>Enter your report</strong><br /><br />",
'report_file_page'				=> "Report this file to a moderator",
'report_file_title'				=> "File Name",
'report_gallery_image_suffix'				=> "- Image",
'report_gallery_comment_suffix'				=> "- Comment",
'report_comment_saved'				=> "Your comment has been saved successfully",
'reports_methods_saved'				=> "Your notification preferences have been saved",
'report_ajax_tab_notif_meth'				=> "Notification Methods",
'active_users_members'				=> "%s members:",
'redirect_delete_report'				=> "Deleting Reports...",
'active_users_title'				=> "%s user(s) are viewing",
'redirect_mark_status'				=> "Marking Reports...",
'report_page_title_unknown'				=> "Unknown Title",
'report_option_delete'				=> "Delete Reports",
'report_option_prune'				=> "Prune Reports...",
'report_post_title'				=> "Report this post to a moderator",
'report_post_url_title'				=> "Topic Title",
'report_post_enter'				=> "<strong>Enter your report</strong>",
'report_basic_submit'				=> "Submit Report",
'report_sending'				=> "Sending Report...",
'report_basic_desc'				=> "Please note: The moderator will be made aware of the link to the page you are reporting.<br />This form is to be used ONLY for reporting objectionable content and is not to be used as a method of communicating with moderators for other reasons.",
'report_basic_enter'				=> "<strong>Enter your report</strong>",
'report_basic_title'				=> "Report this page to a moderator",
'report_basic_url_title'				=> "Reporting Page",
'list_header_comments'				=> "Comments",
'list_header_section'				=> "Section",
'list_header_last_updated'				=> "Last Updated",
'list_header_reports'				=> "Reports",
'older_than'				=> "older than",
'report_prune_days_box'				=> "days",
'main_title'				=> "Report Center",
'list_title'				=> "Reports",
'list_header_title'				=> "Title",
'list_header_updated_by'				=> "Updated By",
'report_prune_message_none'				=> "Nothing to prune...",
'rss_feed_title'				=> "Report Notification",
'report_actions'				=> "Report Options",
'report_actions_mark_optgroup'				=> "Mark Report As",
'report_prune_message_done'				=> "Pruning reports...",
'report_mem_msg'				=> "<b>Enter your report</b>",
'report_mem_page'				=> "Report this profile to a moderator",
'report_mem_title'				=> "Member Name",
'report_section_title_mem'				=> "Member Profile",
'report_section_title_msg'				=> "Private Message",
'r_go'				=> "Go",
'reports_messenger'				=> "Messenger",
'reports_rss_desc'				=> "Shows new reports from the report center.",
'report_section_title_site_downloads'				=> "Download Manager",
'r_with_selected'				=> "With selected reports:",
'status'				=> "Status",
'reporting_title'				=> "Report:",
'view_content'				=> "View content",
'post_button'				=> "Post",
'add_comment_title'				=> "Add Comment",
'no_comments_on_report'				=> "There are no comments on this report yet.",
'comments_h2'				=> "Comments",
'posted_prefix'				=> "Posted",
'reports_h2'				=> "Reports",
'mark_status_as'				=> "Mark as",
'change_status_title'				=> "Change status",
'change_current_status'				=> "Change Current Status",
'current_status'				=> "Current Status:",
'view_report'				=> "View report",
'go_to_section'				=> "Go to section",
'report_updated'				=> "Updated",
'view_member'				=> "View member",
'no_reports'				=> "There are no reports to view",
'configure_notifications'				=> "Configure Notifications",
'report_about_intro'				=> "This report is regarding",
'report_about_pm'				=> "a message titled",
'report_join_pm'				=> "Join the private conversation",
'reported_content_summary'				=> "Reported content from across your community",
'reports_no_plugin'				=> "The report center module for the content you are trying to report is not configured correctly.",
'delete_report'				=> "Delete Report",
'report_view_reported'				=> "View reported content",
'no_permission_addreport'				=> "You do not have permission to add yourself to private conversations.",
'select_all_reports'				=> "Select all reports",
'reports_no_comment_text'				=> "You did not submit a comment to save.",
'subject_reportreply'				=> "<a href='%s'>%s</a> has <a href='%s'>commented</a> on <a href='%s'>reported content</a>",
'report_prune_1'				=> "Prune reports older than",
'report_no_title'				=> "No report title",
 ); 
