<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'help_return_list'				=> "Return to the list of topics",
'help_back_list_title'				=> "Back to list",
'help_read_document'				=> "Read document",
'page_title'				=> "View Help Topics",
'help_topic'				=> "Help Topic",
'choose_file'				=> "Choose a Topic",
'help_topics'				=> "Help Topics",
'help_txt'				=> "Choose a topic from the list, or search for a topic",
'no_help_topics'				=> "There are no help topics yet",
'topic_text'				=> "Here is the topic you chose to view",
 ); 
