<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'likeadded'				=> "Added:",
'likedby'				=> "Followed By",
'freq_daily'				=> "Daily",
'freq_weekly'				=> "Weekly",
'freq_offline'				=> "Only when not online",
'freq_immediate'				=> "Instantly",
'label_anon_desc'				=> "Do not show me in the summary",
'label_anon'				=> "Follow Anonymously",
'label_freq'				=> "Frequency",
'label_notify'				=> "Receive notification",
'fave_title'				=> "%s",
'pg_unfollow_confirm'				=> "Unfollow This Item Now",
'pg_unfollow_text'				=> "<strong>%s</strong>, you have elected to unfollow the item <a href='%s'>%s</a>.<br />If you unfollow, you will no longer receive notifcations when this item is updated.",
'pg_unfollow_title'				=> "Unfollow Item",
'pg_unlike_done'				=> "Item unfollowed successfully",
'pg_no_longer_following'				=> "You are no longer following this item",
 ); 
