<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'email_details'				=> "Enter the email details",
'email_recepient'				=> "Recipient",
'email_sent'				=> "The email has been sent",
'email_friend'				=> "Use this feature to let a friend know about this topic!",
'email_sent_txt'				=> "Thanks, the email has been successfully sent to",
'msg_txt'				=> "Note: By using this form, the recipient will be able to view your email address",
'member_address_title'				=> "Members Email Address",
'title'				=> "Send a page to a friend",
'send_email_to'				=> "Send an email to",
'show_address_text'				=> "You can send this member an email by clicking on the link below. IP.Board does not show email addresses in the topic view to prevent email addresses being harvested by 'spam bots'.",
'redirect'				=> "The email has been sent",
'subject'				=> "Subject",
'message'				=> "Message",
'submit_send'				=> "Send Email",
'to_email'				=> "Send to (Email Address)",
'to_name'				=> "Send to (Person's Name)",
'send_lang'				=> "Send this email in",
'no_message'				=> "You must enter some content for the email",
'no_subject'				=> "You must enter a subject for the email",
'gen_error'				=> "You are not logged in or able to send emails",
'tweet_ok'				=> "Your tweet was successful!",
'email_member'				=> "Email Member",
'emailing_prefix'				=> "Emailing",
'imp_text'				=> "IMPORTANT: To prevent malicious use, all emails sent via this form are logged and the contents recorded and available to the administrators. DO NOT email user names, passwords or any personal details.",
'exceeded_flood'				=> "The mail could not be sent because you have already sent an email within the last %s minutes",
'exceeded_quota'				=> "The mail could not be sent because you have exceeded your allotted quota of %s emails a day",
'fb_share_default'				=> "Share link with your own comment...",
'twitter_share'				=> "Share",
'twitter_chrs_left'				=> "chars left. Shortened URL will be auto-added",
'share_via_twitter'				=> "Share Via Twitter",
'facebook_share'				=> "Share",
'share_via_facebook'				=> "Share Via Facebook",
'fbc_comment_desc'				=> "You can optionally leave a comment below",
'facebook_post_ok'				=> "The link was posted successfully",
'err_reg_code'				=> "The Captcha input was incorrect. Please try again.",
'share_fb_name'				=> "Logged into Facebook as",
 ); 
