<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'm_overrride'				=> "Override group permission masks with...",
'mem_change_button'				=> "Change...",
'mem_posts'				=> "Posts",
 ); 
