<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'topic_noperms'				=> "You do not have permission to access this forum",
'topic_noattach'				=> "The specified topic does not have any attachments",
'leader_all_forums'				=> "All Forums",
'stats_missing_tid'				=> "You must select a valid topic for this feature",
'notopic_attach'				=> "Could not load attachments for the requested topic",
'leader_forums'				=> "Forums",
'leader_last_seen'				=> "Last Active",
'leader_name'				=> "Member Name",
'leader_group'				=> "Group",
'forum_leaders'				=> "The moderating team",
'member_percent'				=> "% of today's posts",
'top_poster_title'				=> "Today's top 20 posters",
'no_info'				=> "No information is available at this time",
'member_joined'				=> "Joined",
'member_posts'				=> "Total Member Posts",
'member_today'				=> "Posts Today",
'member'				=> "Member",
'goto_profile'				=> "Go to profile",
'todays_posters'				=> "Today's Top 20 Posters",
'whoposted_posts'				=> "Posts",
'whoposted_name'				=> "Member name",
'no_forums'				=> "View %s Forums",
'who_replied_title'				=> "Who posted in this topic",
'who_farted'				=> "Who posted in:",
'go_button'				=> "Go",
'm_online'				=> "Online",
 ); 
