<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'emo_title'				=> "Emoticons",
'bbc_after'				=> "We Show",
'bbc_before'				=> "You Type",
'bbc_title'				=> "BB Code",
'bbc_intro'				=> "BB Code is a quick and easy way to add effects or formatting to your posts.<br />It is used in a similar format to HTML tags which you may already be familiar with.<br />Below is a quick guide to the most common BB Code uses.",
 ); 
