<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.6 (34012) on Tue, 30 Dec 2014 12:14:15 +0000 by Satoshi
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'WHERE_print'				=> "Printing a topic",
'WHERE_reports'				=> "Viewing Reports",
'WHERE_profile'				=> "Viewing Profile:",
'WHERE_stats'				=> "Viewing Stats",
'WHERE_invite'				=> "Inviting a friend to the community",
'WHERE_mail'				=> "Contacting member via email",
'WHERE_usercp'				=> "Using User CP",
'WHERE_msg'				=> "Using Personal Messenger",
'WHERE_forward'				=> "Emailing a topic",
'WHERE_search'				=> "Searching...",
'WHERE_help'				=> "Viewing the Help Files",
'WHERE_members'				=> "Viewing the Members List",
'WHERE_online'				=> "Viewing Online List",
'WHERE_reg'				=> "Registering...",
'WHERE_postrep'				=> "Posting in topic:",
'WHERE_postnew'				=> "Posting in forum:",
'WHERE_sr'				=> "Viewing Forum Rules:",
'WHERE_login'				=> "Logging in...",
'WHERE_st'				=> "Viewing Topic:",
'WHERE_portal'				=> "Viewing the portal",
'WHERE_sf'				=> "Viewing Forum:",
'WHERE_boardrules'				=> "Viewing Community Guidelines",
'not_online'				=> "Not online",
'WHERE_calendar'				=> "Viewing the Calendar",
'no_options_available'				=> "No options available",
'board_index'				=> "Viewing Community Index",
'users_online'				=> "Users online",
'online_page_title'				=> "Online Users",
'time'				=> "Time",
'where'				=> "Location",
's_go'				=> "Update",
'member_name'				=> "Member Name",
's_show_mem_all'				=> "Show All Users",
's_show_mem_reg'				=> "Show Registered Only",
's_show_mem_guest'				=> "Show Guests Only",
's_sort_order_asc'				=> "Ascending",
's_sort_order_desc'				=> "Descending",
's_sort_key_click'				=> "Last Click",
's_sort_key_name'				=> "Member Name",
's_by'				=> "Sort by: ",
 ); 
